### ISSUE TITLE
stylish_cmake_parser.parser.CMakeParseException: Expected type "left_paren" but got "1"

### ISSUE THREAD

**Issue by Achllle** [DLu/stylish_cmake_parser#14]
While running `glint_ros`. The error isn't verbose enough to pinpoint what's making it fail so if it's not obvious to you I can build from source and add debugging statements or find out which of my 20+ packages is causing this.

```
Error on Line 39, Char 35
Traceback (most recent call last):
  File "/home/user/.local/bin/glint_ros", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/ros_glint/main.py", line 123, in main
    pkgs = list(find_packages(args.folder))
  File "/home/user/.local/lib/python3.8/site-packages/ros_introspect/package.py", line 270, in find_packages
    yield Package(package_root)
  File "/home/user/.local/lib/python3.8/site-packages/ros_introspect/package.py", line 151, in __init__
    self.add_file(infer_package_file(root / subpath, self))
  File "/home/user/.local/lib/python3.8/site-packages/ros_introspect/package.py", line 129, in infer_package_file
    return subtype(path, package)
  File "/home/user/.local/lib/python3.8/site-packages/ros_introspect/components/cmake.py", line 18, in __init__
    for content in parse_file(self.full_path) or []:
  File "/home/user/.local/lib/python3.8/site-packages/stylish_cmake_parser/__init__.py", line 31, in parse_file
    return parse_commands(s, debug)
  File "/home/user/.local/lib/python3.8/site-packages/stylish_cmake_parser/__init__.py", line 13, in parse_commands
    parser = CMakeParser(s, debug=debug)
  File "/home/user/.local/lib/python3.8/site-packages/stylish_cmake_parser/parser.py", line 71, in __init__
    cmd = self.parse_command()
  File "/home/user/.local/lib/python3.8/site-packages/stylish_cmake_parser/parser.py", line 118, in parse_command
    original += self.match(TokenType.left_paren)
  File "/home/user/.local/lib/python3.8/site-packages/stylish_cmake_parser/parser.py", line 108, in match
    raise CMakeParseException(f'Expected type "{token_type.name}" but got "{self.get_type()}"')
stylish_cmake_parser.parser.CMakeParseException: Expected type "left_paren" but got "1"
```

**Comment by DLu** [comment]
The ambiguity of the location of the failure should be resolved with the next release of the library.
